groups:
    - developer
    - zsh
recipes:
    mac_os_x:
        - osxdefaults::set_computer_name
attributes:
    osxdefaults:
        computername: MyComputerName
    homebrewalt:
        apps:
        cask_apps:
